# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/9"
  config.vm.provider "vmware_desktop"

  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "directory.lambda.corp"
    vm1.vm.network "private_network", type: "dhcp", vmware_network: "VMnet8"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "idp.lambda.corp"
    vm2.vm.network "private_network", type: "dhcp", vmware_network: "VMnet8"
  end
end
