############################################################
# Ping Identity
#
############################################################

pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdataconsole

pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdirectory

pingdelegator:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdelegator

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingfederate

pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingfederate
