############################################################
# Ping Identity
#
############################################################

# PingData Console
pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdataconsole

# PingDirectory Server
pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdirectory
  ingress:
    hosts:
      - host: directory._defaultDomain_
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
      - host: pingdirectory._defaultDomain_
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - directory._defaultDomain_
      - secretName: _defaultTlsSecret_
        hosts:
          - pingdirectory._defaultDomain_