############################################################
# Ping Identity
#
############################################################

# PingData Console
pingdataconsole:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdataconsole

# PingDirectory Server
pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/kowama/lambda-iam.git
    SERVER_PROFILE_PATH: server-profile/baseline/pingdirectory